import csv
from selenium import webdriver
from bs4 import BeautifulSoup
import time

driver = webdriver.Chrome()
url = "url.com"
driver.get(url)

#emul.scroll
total_height = int(driver.execute_script("return document.body.scrollHeight"))
while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(20)
    new_height = int(driver.execute_script("return document.body.scrollHeight"))
    if new_height == total_height:
        break
    total_height = new_height
    
page_source = driver.page_source
driver.quit

soup = BeautifulSoup(page_source, 'html.parser')
anuncios = soup.find_all(" ")

#export .csv
csv_filename = "doc.csv"
with open(csv_filename, "w", newline="", encoding="utf-8") as csv_file:
    csv_writer = csv.writer(csv_file)
    csv_writer.writerow(["y", "x"])
    
    for anuncio in anuncios:
        a = anuncio.find(" ").text
        b = anuncio.find(" ").text
        csv_writer.writerow([a, b])
        #dados/variáveis para coletar
        
print(f"Dados foram salvos com sucesso: {csv_filename}")
